[build]
builder = "railpack"
buildCommand = "npm run build -w backend"
watchPatterns = ["backend/**", "backend.railway.toml"]

[deploy]
startCommand = "npm run start -w backend"
healthcheckTimeout = 100
